-- Insert Districts
INSERT INTO `reference_data` (`category`, `code`, `value`, `sort_order`) VALUES
('district', 'BOB', 'Bobirwa', 1),
('district', 'BOT', 'Boteti', 2),
('district', 'CHH', 'Charles Hill', 3),
('district', 'CHO', 'Chobe', 4),
('district', 'FRA', 'Francistown', 5),
('district', 'GAB', 'Gaborone', 6),
('district', 'GHA', 'Ghanzi', 7),
('district', 'GOO', 'Goodhope', 8),
('district', 'HUK', 'Hukuntsi', 9),
('district', 'JWA', 'Jwaneng', 10),
('district', 'KAN', 'Kanye', 11),
('district', 'KGA', 'Kgatleng', 12),
('district', 'KWE', 'Kweneng', 13),
('district', 'LET', 'Letlhakeng', 14),
('district', 'LOB', 'Lobatse', 15),
('district', 'MAB', 'Mabutsane', 16),
('district', 'MAH', 'Mahalapye', 17),
('district', 'MOG', 'Mogoditshane/Thamaga', 18),
('district', 'MOS', 'Moshupa', 19),
('district', 'NE', 'North-East', 20),
('district', 'NW', 'North-West', 21),
('district', 'OKA', 'Okavango', 22),
('district', 'PAL', 'Palapye', 23),
('district', 'RAM', 'Ramotswa', 24),
('district', 'SP', 'Selibe Phikwe', 25),
('district', 'SER', 'Serowe', 26),
('district', 'TLO', 'Tlokweng', 27),
('district', 'TON', 'Tonota', 28),
('district', 'TSA', 'Tsabong', 29),
('district', 'TUT', 'Tutume', 30);

-- Insert Sub-Districts with parent district references
INSERT INTO `reference_data` (`category`, `code`, `value`, `parent_ref_id`, `sort_order`) VALUES
('sub_district', 'BDIST', 'Bobirwa', (SELECT ref_id FROM reference_data WHERE category='district' AND code='BOB'), 1),
('sub_district', 'BTDIST', 'Boteti', (SELECT ref_id FROM reference_data WHERE category='district' AND code='BOT'), 2),
('sub_district', 'CHDIST', 'Charles Hill', (SELECT ref_id FROM reference_data WHERE category='district' AND code='CHH'), 3),
('sub_district', 'CHODIST', 'Chobe', (SELECT ref_id FROM reference_data WHERE category='district' AND code='CHO'), 4),
('sub_district', 'FRADIST', 'Francistown', (SELECT ref_id FROM reference_data WHERE category='district' AND code='FRA'), 5),
('sub_district', 'GABDIST', 'Gaborone', (SELECT ref_id FROM reference_data WHERE category='district' AND code='GAB'), 6),
('sub_district', 'GHADIST', 'Ghanzi', (SELECT ref_id FROM reference_data WHERE category='district' AND code='GHA'), 7),
('sub_district', 'GOODIST', 'Goodhope', (SELECT ref_id FROM reference_data WHERE category='district' AND code='GOO'), 8),
('sub_district', 'HUKDIST', 'Hukuntsi', (SELECT ref_id FROM reference_data WHERE category='district' AND code='HUK'), 9),
('sub_district', 'JWADIST', 'Jwaneng', (SELECT ref_id FROM reference_data WHERE category='district' AND code='JWA'), 10),
('sub_district', 'KANDIST', 'Kanye', (SELECT ref_id FROM reference_data WHERE category='district' AND code='KAN'), 11),
('sub_district', 'KGADIST', 'Kgatleng', (SELECT ref_id FROM reference_data WHERE category='district' AND code='KGA'), 12),
('sub_district', 'KWEDIST', 'Kweneng', (SELECT ref_id FROM reference_data WHERE category='district' AND code='KWE'), 13),
('sub_district', 'LETDIST', 'Letlhakeng', (SELECT ref_id FROM reference_data WHERE category='district' AND code='LET'), 14),
('sub_district', 'LOBDIST', 'Lobatse', (SELECT ref_id FROM reference_data WHERE category='district' AND code='LOB'), 15),
('sub_district', 'MABDIST', 'Mabutsane', (SELECT ref_id FROM reference_data WHERE category='district' AND code='MAB'), 16),
('sub_district', 'MAHDIST', 'Mahalapye', (SELECT ref_id FROM reference_data WHERE category='district' AND code='MAH'), 17),
('sub_district', 'MOGDIST', 'Mogoditshane/Thamaga', (SELECT ref_id FROM reference_data WHERE category='district' AND code='MOG'), 18),
('sub_district', 'MOSDIST', 'Moshupa', (SELECT ref_id FROM reference_data WHERE category='district' AND code='MOS'), 19),
('sub_district', 'NEDIST', 'North-East', (SELECT ref_id FROM reference_data WHERE category='district' AND code='NE'), 20),
('sub_district', 'NWDIST', 'North-West', (SELECT ref_id FROM reference_data WHERE category='district' AND code='NW'), 21),
('sub_district', 'OKADIST', 'Okavango', (SELECT ref_id FROM reference_data WHERE category='district' AND code='OKA'), 22),
('sub_district', 'PALDIST', 'Palapye', (SELECT ref_id FROM reference_data WHERE category='district' AND code='PAL'), 23),
('sub_district', 'RAMDIST', 'Ramotswa', (SELECT ref_id FROM reference_data WHERE category='district' AND code='RAM'), 24),
('sub_district', 'SPDIST', 'Selibe Phikwe', (SELECT ref_id FROM reference_data WHERE category='district' AND code='SP'), 25),
('sub_district', 'SERDIST', 'Serowe', (SELECT ref_id FROM reference_data WHERE category='district' AND code='SER'), 26),
('sub_district', 'TLODIST', 'Tlokweng', (SELECT ref_id FROM reference_data WHERE category='district' AND code='TLO'), 27),
('sub_district', 'TONDIST', 'Tonota', (SELECT ref_id FROM reference_data WHERE category='district' AND code='TON'), 28),
('sub_district', 'TSADIST', 'Tsabong', (SELECT ref_id FROM reference_data WHERE category='district' AND code='TSA'), 29),
('sub_district', 'TUTDIST', 'Tutume', (SELECT ref_id FROM reference_data WHERE category='district' AND code='TUT'), 30);

-- Insert Regions
INSERT INTO `reference_data` (`category`, `code`, `value`, `sort_order`) VALUES
('region', 'CEN', 'Central', 1),
('region', 'KGA', 'Kgalagadi', 2),
('region', 'SOU', 'South', 3),
('region', 'SE', 'South East', 4),
('region', 'KGT', 'Kgatleng', 5),
('region', 'NE', 'North East', 6),
('region', 'KWN', 'Kweneng', 7),
('region', 'CHO', 'Chobe', 8),
('region', 'NW', 'North West', 9),
('region', 'GAN', 'Gantsi', 10);

-- Insert Sub-Regions
INSERT INTO `reference_data` (`category`, `code`, `value`, `sort_order`) VALUES
('sub_region', 'SBOB', 'Bobirwa', 1),
('sub_region', 'SBOT', 'Boteti', 2),
('sub_region', 'SCHH', 'Charles Hill', 3),
('sub_region', 'SCHO', 'Chobe', 4),
('sub_region', 'SFRA', 'Francistown', 5),
('sub_region', 'SGAB', 'Gaborone', 6),
('sub_region', 'SGAN', 'Gantsi', 7),
('sub_region', 'SGOO', 'Goodhope', 8),
('sub_region', 'SGUM', 'Gumare', 9),
('sub_region', 'SJWA', 'Jwaneng/Mabutsane', 10),
('sub_region', 'SKAN', 'Kanye', 11),
('sub_region', 'SKN', 'Kgalagadi North', 12),
('sub_region', 'SKS', 'Kgalagadi South', 13),
('sub_region', 'SKGT', 'Kgatleng', 14),
('sub_region', 'SLEN', 'Lentsweletau', 15),
('sub_region', 'SLET', 'Letlhakeng', 16),
('sub_region', 'SLOB', 'Lobatse', 17),
('sub_region', 'SMAH', 'Mahalapye', 18),
('sub_region', 'SMAU', 'Maun', 19),
('sub_region', 'SMOG', 'Mogoditshane/Thamaga', 20),
('sub_region', 'SMOL', 'Molepolole', 21),
('sub_region', 'SMOS', 'Moshupa', 22),
('sub_region', 'SNE', 'North-East', 23),
('sub_region', 'SPAL', 'Palapye', 24),
('sub_region', 'SSEF', 'Sefhare', 25),
('sub_region', 'SSP', 'Selibe Phikwe', 26),
('sub_region', 'SSER', 'Serowe', 27),
('sub_region', 'SSHA', 'Shakawe', 28),
('sub_region', 'SSHO', 'Shoshong', 29),
('sub_region', 'SSE', 'South East', 30),
('sub_region', 'STON', 'Tonota', 31),
('sub_region', 'STUT', 'Tutume', 32);
